"""empty message

Revision ID: 1008c35c36b3
Revises: ac76a7923c70
Create Date: 2024-03-03 13:31:24.908808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1008c35c36b3'
down_revision = 'ac76a7923c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goods_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('goods_name', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('goods_name')
        batch_op.drop_column('goods_id')

    # ### end Alembic commands ###
