"""empty message

Revision ID: 4048b7166cf0
Revises: 76962eeee6e5
Create Date: 2024-02-07 10:15:45.666432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4048b7166cf0'
down_revision = '76962eeee6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registered_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_on', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
