"""empty message

Revision ID: 76962eeee6e5
Revises: 
Create Date: 2024-02-07 10:01:27.347570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76962eeee6e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_ref', sa.Integer(), nullable=True),
    sa.Column('goods_code', sa.String(), nullable=True),
    sa.Column('goods_name', sa.String(), nullable=True),
    sa.Column('stock_dc_ref', sa.Integer(), nullable=True),
    sa.Column('stock_dc_code', sa.String(), nullable=True),
    sa.Column('stock_dc_name', sa.String(), nullable=True),
    sa.Column('is_batch', sa.Integer(), nullable=True),
    sa.Column('carton_type', sa.Float(), nullable=True),
    sa.Column('on_hand_qty', sa.Float(), nullable=True),
    sa.Column('order_point', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('shop_name', sa.String(length=30), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('brand')
    # ### end Alembic commands ###
